In [1]:
import numpy as np

### Boolean Indexing

In [3]:
# We create a 5 x 5 ndarray that contains integers from 0 to 24
X = np.arange(25).reshape(5, 5)
print(X)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [4]:
print('The elements in X that are greater than 10:', X[X > 10])

The elements in X that are greater than 10: [11 12 13 14 15 16 17 18 19 20 21 22 23 24]


In [5]:
print('The elements in X that less than or equal to 7:', X[X <= 7])

The elements in X that less than or equal to 7: [0 1 2 3 4 5 6 7]


In [6]:
print('The elements in X that are between 10 and 17:', X[(X > 10) & (X < 17)])

The elements in X that are between 10 and 17: [11 12 13 14 15 16]


In [7]:
X[(X > 10) & (X < 17)] = -1
print(X)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 -1 -1 -1 -1]
 [-1 -1 17 18 19]
 [20 21 22 23 24]]


### Set Operation

In [8]:
x = np.array([1,2,3,4,5])
y = np.array([6,7,2,8,4])

In [9]:
print('The elements that are both in x and y:', np.intersect1d(x,y))

The elements that are both in x and y: [2 4]


In [10]:
print('The elements that are in x that are not in y:', np.setdiff1d(x,y))

The elements that are in x that are not in y: [1 3 5]


In [11]:
print('All the elements of x and y:',np.union1d(x,y))

All the elements of x and y: [1 2 3 4 5 6 7 8]


### numpy.ndarray.sort method
ndarray.sort(axis=-1, kind=None, order=None)

Like with other functions we saw before, the sort can be used as a method as well as a function. The difference lies in how the data is stored in memory in this case.

* When `numpy.sort()` is used as a function, it sorts the ndrrays out of place, meaning, that it doesn't change the original ndarray being sorted.
* On the other hand, when you use `numpy.ndarray.sort()` as a method, ndarray.sort() sorts the ndarray in place, meaning, that the original array will be changed to the sorted one.

#### Sort arrays using sort function

In [12]:
x = np.random.randint(1, 11, size=(10,))
print(x)

[ 5 10  1  2  9  9  3  7  6  4]


In [17]:
## use sort as a function
print('Sorted x (out of place):', np.sort(x))

Sorted x (out of place): [ 1  2  3  4  5  6  7  9  9 10]


In [18]:
# x after sort
print(x)

[ 5 10  1  2  9  9  3  7  6  4]


In [19]:
# Returns the sorted unique elements of an array
print(np.unique(x))

[ 1  2  3  4  5  6  7  9 10]


In [20]:
## Use sort as a method
print(x)

[ 5 10  1  2  9  9  3  7  6  4]


In [22]:
x.sort()

In [23]:
print(x)

[ 1  2  3  4  5  6  7  9  9 10]


### Sort Rank2 array by specific axis

In [24]:
X = np.random.randint(1,11,size=(5,5))
print(X)

[[ 5  9  1  5  5]
 [ 8  4  2  6  7]
 [10  7  5 10  5]
 [ 5  2  6 10  4]
 [ 1  7  9  9  7]]


In [28]:
print('X with sorted default axis -1 : \n', np.sort(X, axis=-1))

X with sorted default axis -1 : 
 [[ 1  5  5  5  9]
 [ 2  4  6  7  8]
 [ 5  5  7 10 10]
 [ 2  4  5  6 10]
 [ 1  7  7  9  9]]


In [25]:
print('X with sorted columns :\n', np.sort(X, axis = 0))

X with sorted columns :
 [[ 1  2  1  5  4]
 [ 5  4  2  6  5]
 [ 5  7  5  9  5]
 [ 8  7  6 10  7]
 [10  9  9 10  7]]


In [26]:
print('X with sorted rows :\n', np.sort(X, axis = 1))

X with sorted rows :
 [[ 1  5  5  5  9]
 [ 2  4  6  7  8]
 [ 5  5  7 10 10]
 [ 2  4  5  6 10]
 [ 1  7  7  9  9]]
