In [1]:
import numpy as np

In [13]:
# Delete element - np.delete(ndarray, elements, axis)

# We create a rank 1 ndarray 
x = np.array([1, 2, 3, 4, 5])

# We create a rank 2 ndarray
Y = np.array([[1,2,3],[4,5,6],[7,8,9]])

print("Original_x:", x)

x = np.delete(x, [0, 4])

print("Modified_x:", x)

print("OriginalY: \n", Y)

w = np.delete(Y, 0, axis=0)
print("ModifiedY1:\n", w)

v = np.delete(Y, [0, 2], axis=1)
print("ModifiedY2: \n", v)

Original_x: [1 2 3 4 5]
Modified_x: [2 3 4]
OriginalY: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
ModifiedY1:
 [[4 5 6]
 [7 8 9]]
ModifiedY2: 
 [[2]
 [5]
 [8]]


In [14]:
# Append - np.append(ndarray, values, axis)

# We create a rank 1 ndarray 
x = np.array([1, 2, 3, 4, 5])

# We create a rank 2 ndarray 
Y = np.array([[1,2,3],[4,5,6]])

print("original x: ", x)

x_modified1 = np.append(x, 6)
print("modified_x1: ", x_modified1)

x_modified2 = np.append(x, [7, 8])
print("modified_x2: ", x_modified2)

print("original Y: \n", Y)

Y_modified1 = np.append(Y, [[7, 8, 9]], axis=0)
print("modified_Y1: \n", Y_modified1)

Y_modified2 = np.append(Y, [[7], [8]], axis=1)
print("modified_Y2: \n", Y_modified2)

original x:  [1 2 3 4 5]
modified_x1:  [1 2 3 4 5 6]
modified_x2:  [1 2 3 4 5 7 8]
original Y: 
 [[1 2 3]
 [4 5 6]]
modified_Y1: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
modified_Y2: 
 [[1 2 3 7]
 [4 5 6 8]]


In [20]:
# Insert - np.insert(ndarray, index, elements, axis)

# rank1 array
arr1 = np.array([1, 2, 5, 6, 7])

# rank2 array
arr2 = np.array([[1, 2, 3], [7, 8, 9]])

print("Original_arr1: ", arr1)
arr1_modified = np.insert(arr1, 2, [3, 4])
print("Modified arr1: ", arr1_modified)

print("\n")

print("Original_arr2: \n", arr2)
arr2_modified1 = np.insert(arr2, 1, [[4, 5, 6]], axis=0)
print("Modified arr2 one: \n", arr2_modified1)

print("\n")

arr2_modified2 = np.insert(arr2, 1, 5, axis=1)
print("Modified arr2 two: \n", arr2_modified2)

Original_arr1:  [1 2 5 6 7]
Modified arr1:  [1 2 3 4 5 6 7]


Original_arr2: 
 [[1 2 3]
 [7 8 9]]
Modified arr2 one: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


Modified arr2 two: 
 [[1 5 2 3]
 [7 5 8 9]]


In [24]:
# numpy.hstack & numpy.vstack

x = np.array([1, 2])

y = np.array([[3, 4], [5, 6]])

print("OriginalX: ", x)
print("OriginalY: \n", y)
v = np.vstack((x, y))
print("Vstack: \n", v)
print("\n")

h = np.hstack((y, x.reshape(2, 1)))
print("Hstack: \n", h)

OriginalX:  [1 2]
OriginalY: 
 [[3 4]
 [5 6]]
Vstack: 
 [[1 2]
 [3 4]
 [5 6]]


Hstack: 
 [[3 4 1]
 [5 6 2]]
