In [1]:
import numpy as np

#### ndarray[start:end]
#### ndarray[start:]
#### ndarray[:end]
*start* is included and *end* is excluded

### Slicing a 2D array

In [12]:
X = np.arange(20).reshape(4, 5)

print(X)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [4]:
Z = X[1:4, 2:5]
print(Z)

[[ 7  8  9]
 [12 13 14]
 [17 18 19]]


In [5]:
W = X[1:,2:5]
print(W)

[[ 7  8  9]
 [12 13 14]
 [17 18 19]]


In [8]:
Y = X[:3,2:5]
print(Y)

[[ 2  3  4]
 [ 7  8  9]
 [12 13 14]]


In [9]:
v = X[2,:]
print(v)

[10 11 12 13 14]


In [10]:
q = X[:,2]
print(q)

[ 2  7 12 17]


In [13]:
R = X[:,2:3] # to create rank2 version of above cell
print(R)

[[ 2]
 [ 7]
 [12]
 [17]]


### Slicing and editing elements in a 2D array

In [15]:
X = np.arange(20).reshape(4, 5)
print(X)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [16]:
Z = X[1:4,2:5]
print(Z)

[[ 7  8  9]
 [12 13 14]
 [17 18 19]]


In [19]:
Z[2, 2] = 555
print(Z)

[[  7   8   9]
 [ 12  13  14]
 [ 17  18 555]]


In [18]:
print(X)

[[  0   1   2   3   4]
 [  5   6   7   8   9]
 [ 10  11  12  13  14]
 [ 15  16  17  18 555]]


We can clearly see in the above example that if we make changes to Z, X changes as well.

### Using of copy()

In [27]:
X = np.arange(20).reshape(4, 5)
print(X)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [28]:
Z = np.copy(X[1:4,2:5])
print(Z)

[[ 7  8  9]
 [12 13 14]
 [17 18 19]]


In [29]:
W = X[1:4,2:5].copy()
print(W)

[[ 7  8  9]
 [12 13 14]
 [17 18 19]]


In [30]:
Z[2,2] = 555
print(Z)

[[  7   8   9]
 [ 12  13  14]
 [ 17  18 555]]


In [35]:
print(X)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [33]:
print(W)

[[ 7  8  9]
 [12 13 14]
 [17 18 19]]


In [34]:
W[2, 2] = 444
print(W)

[[  7   8   9]
 [ 12  13  14]
 [ 17  18 444]]


### Use an array as indices to either make slices, select, or change elements

In [36]:
X = np.arange(20).reshape(4, 5)
print(X)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [38]:
indices = np.array([1,3])
print(indices)

[1 3]


In [39]:
# We use the indices ndarray to select the 2nd and 4th row of X
Y = X[indices,:]
print(Y)

[[ 5  6  7  8  9]
 [15 16 17 18 19]]


In [40]:
Z = X[:, indices]
print(Z)

[[ 1  3]
 [ 6  8]
 [11 13]
 [16 18]]


### Use an array as indices to extract specific rows from a rank 2 ndarray

In [44]:
X = np.random.randint(1,20, size=(50,5))
print("Shape of X is: ", X.shape)
print()
print(X)

Shape of X is:  (50, 5)

[[ 3  4 16  3  9]
 [ 3 12 14 18 19]
 [ 7  2  4 14  3]
 [15  9  8  1 19]
 [12 16  6 14  9]
 [ 6  9 18 15  8]
 [10  3  3 10  1]
 [ 5 12  9  5 10]
 [ 6  9 18 19  7]
 [17  2 12  6 18]
 [18 15 12 12  3]
 [14 14 17 15  8]
 [17  5  9  3  6]
 [10 18  2 13  8]
 [ 6 16 12  8 15]
 [12  7  7 17 18]
 [15 10  8  9 12]
 [ 8  8 10 15 11]
 [10 11 14  9  3]
 [18  7 19 17 15]
 [18 17 12 10  3]
 [19 14 18 14 15]
 [14 19 18  1 17]
 [ 2  3  8 18 16]
 [ 1 13  4 15 12]
 [15 15 19  2 18]
 [ 3  3 10 19 12]
 [10  6 14 16  9]
 [15 16 15 15  1]
 [15 15  7  1  4]
 [ 7 18 12  3  9]
 [10  8  4  6 10]
 [ 4  7 18  6  6]
 [15 13 10  7  6]
 [ 8 14 14 13 18]
 [ 4  6  2  6  2]
 [19 13 17 18 16]
 [ 6 10  7 10 10]
 [11 11  5  5 15]
 [13  2  3  2 11]
 [10 15  1  8  6]
 [ 7 13  4  8 15]
 [14  3  5  9 19]
 [18  3 17  3  4]
 [ 9  9 11 19 14]
 [19 15  9 18  5]
 [19  6 11 11 15]
 [ 9  9  7 18 16]
 [ 4  6 19  7 10]
 [12 10  5  1  1]]


In [45]:
# Create a rank 1 ndarray that contains a randomly chosen 10 values between `0` to `len(X)` (50)
# The row_indices would represent the indices of rows of X
row_indices = np.random.randint(0,50, size=10)
print("Random 10 indices are: ", row_indices)

Random 10 indices are:  [45 31  9 33 12 24 18 33 46  3]


In [46]:
# To Do 1 - Print those rows of X whose indices are represented by entire row_indices ndarray
# Hint - Use the row_indices ndarray to select specified rows of X
X_subset = X[row_indices, :]
print(X_subset)

[[19 15  9 18  5]
 [10  8  4  6 10]
 [17  2 12  6 18]
 [15 13 10  7  6]
 [17  5  9  3  6]
 [ 1 13  4 15 12]
 [10 11 14  9  3]
 [15 13 10  7  6]
 [19  6 11 11 15]
 [15  9  8  1 19]]


In [47]:
# To Do 2 - Print those rows of X whose indices are present in row_indices[4:8]
X_subset = X[row_indices[4:8], :]
print(X_subset)

[[17  5  9  3  6]
 [ 1 13  4 15 12]
 [10 11 14  9  3]
 [15 13 10  7  6]]


### np.diag(ndarray, k=N)

In [49]:
# We create a 4 x 5 ndarray that contains integers from 0 to 24
X = np.arange(25).reshape(5, 5)
print(X)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [51]:
# We print the elements in the main diagonal of X
print('z =', np.diag(X))

z = [ 0  6 12 18 24]


In [52]:
# We print the elements above the main diagonal of X
print('y =', np.diag(X, k=1))

y = [ 1  7 13 19]


In [53]:
# We print the elements above the main diagonal of X
print('y =', np.diag(X, k=3))

y = [3 9]


In [54]:
# We print the elements below the main diagonal of X
print('w = ', np.diag(X, k=-1))

w =  [ 5 11 17 23]


In [55]:
# We print the elements below the main diagonal of X
print('w = ', np.diag(X, k=-4))

w =  [20]


### np.unique(array, return_index=False, return_inverse=False, return_counts=False, axis=None)

In [56]:
# Create 3 x 3 ndarray with repeated values
X = np.array([[1,2,3],[5,2,8],[1,2,3]])
print(X)

[[1 2 3]
 [5 2 8]
 [1 2 3]]


In [57]:
# We print the unique elements of X 
print('The unique elements in X are:',np.unique(X))

The unique elements in X are: [1 2 3 5 8]
